-- SQL schema for fivem_staff_orchestra database
CREATE TABLE Users (id INT AUTO_INCREMENT PRIMARY KEY, discord_id VARCHAR(50), username VARCHAR(100), rank INT);
CREATE TABLE StaffRanks (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50), permissions TEXT);
CREATE TABLE CalendarEvents (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100), start DATETIME, end DATETIME);
CREATE TABLE Players (id INT AUTO_INCREMENT PRIMARY KEY, license VARCHAR(100), name VARCHAR(100));
CREATE TABLE TrustScores (id INT AUTO_INCREMENT PRIMARY KEY, player_id INT, score INT, reason TEXT);
CREATE TABLE Punishments (id INT AUTO_INCREMENT PRIMARY KEY, player_id INT, type VARCHAR(10), reason TEXT, date DATETIME);
CREATE TABLE Characters (id INT AUTO_INCREMENT PRIMARY KEY, player_id INT, name VARCHAR(100), stats TEXT);
CREATE TABLE Vehicles (id INT AUTO_INCREMENT PRIMARY KEY, plate VARCHAR(20), owner_id INT, inventory TEXT);
CREATE TABLE Properties (id INT AUTO_INCREMENT PRIMARY KEY, address VARCHAR(100), owner_id INT, inventory TEXT);
CREATE TABLE Leaderboards (id INT AUTO_INCREMENT PRIMARY KEY, category VARCHAR(50), data TEXT);
CREATE TABLE Logs (id INT AUTO_INCREMENT PRIMARY KEY, type VARCHAR(50), message TEXT, timestamp DATETIME);
CREATE TABLE PanelSettings (id INT AUTO_INCREMENT PRIMARY KEY, key_name VARCHAR(50), value TEXT);
CREATE TABLE StaffGroups (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50), permissions TEXT);
CREATE TABLE DiscordLogs (id INT AUTO_INCREMENT PRIMARY KEY, channel VARCHAR(100), message TEXT, timestamp DATETIME);